### ISSUE TITLE
[Bug] Datatable issue 

### ISSUE THREAD

**Issue by MnlLBD1** [creativetimofficial/ct-soft-ui-dashboard-pro#32]
### Version
soft-dashboard-pro-html-v1.0.5
### Reproduction link
http://cargo-clients.techaccio.com
### Operating System
Shared hosting
### Device
All devices
### Browser & Version
Safari, Chrome and brave
### Steps to reproduce
Hello ,

I have purchased your theme and included all the assets in mu Laravel project , but I have an issue with data tables , Pagination and show selector doesn't work , you can verify it here in flash quotes or other pages : http://cargo-clients.techaccio.com/
Login : Clien1@client1.com , it is the same for password .

### What is expected?
having sorting , pagination ,search and showing by number working correctly 
### What is actually happening?
Datatables sorting , pagination ,search and showing by number doesn't work correctly 

---

**Comment by rarestoma** [comment]
Hi @MnlLBD1,

Thank you for working with our products.

I tried to log in using `Clien1@client1.com` and `Clien1@client1.com` as a password but I get '`Invalid credentials please use your client credentials or contact support`'.

Thank you,
Rares

**Comment by MnlLBD1** [comment]
Please try this one , admin : karim@logisarl.com , password :  karim@logisarl.com

**Comment by rarestoma** [comment]
Hi @MnlLBD1,

Now I can log in. Can you please add more entries(about 10) so I can test the search and the pagination? Currently there is just one.

Thank you, 
Rares

**Comment by MnlLBD1** [comment]
hello, there is 12 entries in the part : Flash Quotes , you can test it and see

**Comment by MnlLBD1** [comment]
Still waiting for your reply, 
Thank you

**Comment by rarestoma** [comment]
Hi @MnlLBD1,

I just entered now but I see 0 entries (see image attached).

<img width="1660" alt="Captură de ecran din 2021-12-20 la 11 48 18 a m" src="https://user-images.githubusercontent.com/27827318/146747366-4f94b8f0-bd4c-4d08-ba80-25e2a4fea6cc.png">

Thank you,
Rares

**Comment by MnlLBD1** [comment]
Please verify now

**Comment by rarestoma** [comment]
Hi,

As I see, the table is initialized correctly.

The problem might be from the chart initialization in the /flashquotes page. Please remove the script that contains the chart initialization:

```
<script>
var ctx = document.getElementById("chart-bars").getContext("2d");
...
</script>
```

Let's see if it works now.

Thank you,
Rares

**Comment by MnlLBD1** [comment]
Done it, but nothing changes

**Comment by shuidiyoushu** [comment]
Has the problem been solved? I have encountered the same problem and still can't solve it

**Comment by shuidiyoushu** [comment]
![微信图片_20220123222656](https://user-images.githubusercontent.com/69995892/150683276-2e41228a-fc22-4a8f-ba14-0afe16188fd1.png)

**Comment by shuidiyoushu** [comment]
@rarestoma 
![微信图片_20220123223512](https://user-images.githubusercontent.com/69995892/150683702-759add96-15f2-4ed5-a82c-3d1b55b752fd.png)
![微信图片_20220123223525](https://user-images.githubusercontent.com/69995892/150683703-2ae6e9a9-6798-481d-8a25-2ac7ba0ab4f2.png)

**Comment by rarestoma** [comment]
Hi @shuidiyoushu,

Thank you for working with our products.

Can you please give me the link to your application so I can see exactly what happens?

Thank you,
Rares
